# Start window numbering at 1 (not 0)
set -g base-index 1
setw -g pane-base-index 1

# Enable mouse support
set -g mouse on

# Enable system-clpiboard support
set -g set-clipboard on

# Increase history limit
set -g history-limit 10000

# 256 color support
set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'

# Status bar position
set -g status-position top

# Status bar colors
set -g status-style 'bg=#222436 fg=#c8d3f5'
#set -g status-left-length 20
set -g status-right-length 50

# Status bar content
set -g status-left ''
set -g status-right '#[fg=#30363d]│#[fg=#8b949e] %H:%M #[fg=#30363d]│#[fg=#8b949e] %d-%b-%Y #[fg=#30363d]│'
set -ga status-right '#[bg=colour214,fg=colour237] #(whoami) ' # show username
#set -ga status-right '#[bg=colour214,fg=colour237] #S ' # show session name

# Window status
setw -g window-status-format ' #[fg=colour244]#I:#[fg=colour=250]#W '
setw -g window-status-current-format '#[bg=#00e68a,fg=colour237,bold][ #I:' # window ID
setw -ga window-status-current-format '#W ]' #window name

# Pane border colors
set -g pane-border-style 'fg=#30363d'
set -g pane-active-border-style 'fg=#00e68a'

# Message styling
set -g message-style 'bg=#00e68a fg=#000000 bold'
